@startuml
|Admin|
start
:Tạo quảng cáo mới;
|Hệ thống|
:Yêu cầu nhập thông tin quảng cáo;
|Admin|
repeat
|Admin|
:Nhập thông tin;
|Hệ thống|
:Xử lý;
repeat while(Kiểm tra thông tin) is (không hợp lệ)
|Hệ thống|
:Lưu quảng cáo mới;
stop

@enduml